 # Server
server.port=8080

spring.application.name=video-processing-backend

# File Upload
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

# Temp Folders
app.temp.input-dir=temp/input
app.temp.output-dir=temp/output

# FFmpeg paths \u2014 Linux paths for Render
app.ffmpeg.path=/usr/local/bin/ffmpeg
app.ffprobe.path=/usr/local/bin/ffprobe

# Logging
logging.level.com.videoprocessor=DEBUG
logging.level.org.springframework.web=INFO